export const FORM_INITIALISATION = 'FORM_INITIALISATION';
export const SET_FORM_SUBMITTING = 'SET_FORM_SUBMITTING';
export const RESET_FORM = 'RESET_FORM';
export const UPDATE_FORM = 'UPDATE_FORM';
export const SET_FORM_SUBMITTED = 'SET_FORM_SUBMITTED';
