import type {
  HasIn,
  SetIn,
  GetIn,
  Merge,
  DeleteIn,
  Keys,
  CloneDeep,
  Is,
  IsList,
  ListIncludes,
  ListSize,
  IsImmutable,
  ToJS,
} from './common';

export type DataFunctions = {|
  fromJS: CloneDeep,
  map: CloneDeep,
  hasIn: HasIn,
  setIn: SetIn,
  getIn: GetIn,
  merge: Merge,
  deleteIn: DeleteIn,
  keys: Keys,
  list: CloneDeep,
  is: Is,
  isList: IsList,
  listIncludes: ListIncludes,
  listSize: ListSize,
  isImmutable: IsImmutable,
  toJS: ToJS,
|};
